### ISSUE TITLE
MultiMarkdown Support Feature Request

### ISSUE THREAD

**Issue by macdrifter** [dtjm/textdropapp.com#105]
Add support for MultiMarkdown preview instead of plain Markdown. MultiMarkdown supports common features like footnotes and tables, which Markdown does not.

**Comment by dtjm** [comment]
I've been looking into this but haven't been able to find a parser in JavaScript. If those are the particular features you need then I might be able to hack them into the current parser.

**Comment by macdrifter** [comment]
I didn't realize it was rendering with JS. That explains why it's so fast. It's a pretty low priority so it can wait for a proper solution. I wouldn't want it to hold up anything else.

**Comment by dtjm** [comment]
Yeah it's actually rendering as you type in a Web Worker thread in the background, so when you turn on preview it's just showing what's already rendered. 

I'll keep it in the FEATURES milestone and come back to it later.

**Comment by dtjm** [comment]
MultiMarkdown will be released in 3.6 which I'm prepping right now.

**Comment by macdrifter** [comment]
You rock! How'd you do it in JavaScript?

Gabe

**Comment by dtjm** [comment]
Well, I tried translating Fletcher Penney's PEG grammar to peg.js but it wasn't going to happen. So instead I went the server side route. I built a Node.js module from his libraries and made a web service out of it. 

It's a little less snappy but it should be completely accurate. 

Hopefully I'll have it done by the weekend.

Sam
