### ISSUE TITLE
Hard tabs

### ISSUE THREAD

**Issue by dtjm** [dtjm/textdropapp.com#138]
> I'm having trouble with lists in textdrop app. I need to add a hard tab in front of lists of todo items inorder for them to be recognised by my todo app but textdropapp seems to add a number of spaces instead of a proper tab when I look at the formatting code. I can't find anything about tabs in the markdown help. Is there anyway of getting a hard tab?

**Comment by jkishner** [comment]
Ditto. I just emailed support about this, a hard tab in TextDropApp doesn't sync correctly with TaskPaper for iOS.

**Comment by dtjm** [comment]
Hard tabs are now available by setting the preference in your account page: https://www.textdropapp.com/account

**Comment by jkishner** [comment]
I have tried in both Firefox and Chrome for Mac, I cannot get the checkbox
checked, i.e., I cannot select it to enable hard tabs.

**Comment by dtjm** [comment]
What versions are you running?

**Comment by jkishner** [comment]
Chrome 22.0.1229.79
Firefox 13.0.1

I use textdropapp on a work computer, so I can't upgrade FF without jumping
through hoops.

**Comment by dtjm** [comment]
Ok no problem ill take a look.

**Comment by dtjm** [comment]
Ok stupid bug on my part....try clicking off the checkbox, e.g. Click on the words "hard tabs"

**Comment by jkishner** [comment]
That works in that I can get the box checked, but when I type "\t" it just
types "\t" it doesn't create a hard tab.

**Comment by dtjm** [comment]
You don't actually have to type "\t", just hit the tab key and it should use a hard tab character.

**Comment by jkishner** [comment]
Ah, I see. It works as advertised then. Thank you so much for implementing
this.

**Comment by dtjm** [comment]
Cool, thanks for helping me test it. 

/Sam
