### ISSUE TITLE
Opening, pasting, and exiting does not save changes to file

### ISSUE THREAD

**Issue by andrewxhonson** [dtjm/textdropapp.com#151]
If you open a file, paste something into it, and exit, the file doesn't change. It looks like only a keystroke that types into the textarea will trigger saving the file, so if I paste and then press a couple letters and delete them, it saves properly.

**Comment by dtjm** [comment]
Thanks! I'll be sure to trigger the save on the paste event.

**Comment by andrewxhonson** [comment]
I think the same thing happens if you only cut. I don't know what else
would cause it, keystrokes that don't type something. Thanks!

**Comment by dtjm** [comment]
Freddy, I'm not able to reproduce this. What browser are you experiencing this in?

**Comment by dtjm** [comment]
I'm going to close this for now, but we can re-open it once I'm able to reproduce it.
