### ISSUE TITLE
Numeric Folder Names in Wrong Order

### ISSUE THREAD

**Issue by gerrymanoim** [dtjm/textdropapp.com#154]
Instead of storting folders in the order "1, 2,...10", Textdrop sorts in the order "1, 10, 2, 3,..9"

Example in Textdrop:
![2a](https://f.cloud.github.com/assets/194147/55445/2cbb0ab8-5acb-11e2-90ce-e037b125f0e3.png)

Example in Finder:
![2b](https://f.cloud.github.com/assets/194147/55447/3a3b4d74-5acb-11e2-8eec-883dbba94a17.png)

**Comment by dtjm** [comment]
Thanks, I think I can roll this into the next release.

**Comment by dtjm** [comment]
targeting for milestone 3.8.1
