### ISSUE TITLE
Print Dropbox Preview

### ISSUE THREAD

**Issue by segiddins** [dtjm/textdropapp.com#157]
It would be awesome to be able to print the rendered markdown in a pretty format (something that matches ST2's Markdown Preview would be amazing)

**Comment by dtjm** [comment]
Hi, are you talking about something different than the built-in MultiMarkdown preview? (Press Shift-Ctrl-M while in the text editor mode).

Please provide a screenshot as an example, thanks.

**Comment by segiddins** [comment]
Hrm, that's odd. Before I couldn't get it to print without some lines down the left, but just now it worked.

-Samuel E. Giddins
http://segiddins.me

On Jan 11, 2013, at 8:02 PM, dtjm notifications@github.com wrote:

Hi, are you talking about something different than the built-in MultiMarkdown preview? (Press Shift-Ctrl-M while in the text editor mode).

Please provide a screenshot as an example, thanks.

**Comment by dtjm** [comment]
Ok, I'll close this for now, just post another comment here if it happens again.
