### ISSUE TITLE
nvALT style handling of @done 

### ISSUE THREAD

**Issue by superhungry** [dtjm/textdropapp.com#170]
NVAlt calls this feature
"TaskPaper-compatible strikethrough formatting using the “@done” tag"

any way textdropapp can suport this?

**Comment by dtjm** [comment]
Hi,

At this point, it's not possible because I'm using a <textarea> element, but if that changes I'll keep this in mind.

Thanks,
/sam

**Comment by dtjm** [comment]
+1

> As a first step would be syntax highlighting very useful. After that
> maybe a shortcut for tagging the tasks with @done(YYYY-MM-DD).

**Comment by dtjm** [comment]
Should be resolved by https://trello.com/c/cd22lfZS which will add TaskPaper support.
