### ISSUE TITLE
Can't access beta site

### ISSUE THREAD

**Issue by sa1f** [dtjm/textdropapp.com#18]
http://tree.textdropapp.com/home/Beta%20testing%20program    <--   going here gives an application error. Clearing cookies, changing browsers doesn't help.

**Comment by dtjm** [comment]
Hmm....not having this issue right now. Anyone else having this problem?

**Comment by sa1f** [comment]
Weird... Works fine now. All basic functions work fine! Might want to check your logs still.

**Comment by dtjm** [comment]
Great! Thanks for testing. Logs look there was an error on another page that crashed the server so you probably tried to load the page while it was down.
