### ISSUE TITLE
Account preferences should be saved

### ISSUE THREAD

**Issue by elcste** [dtjm/textdropapp.com#187]
The account preferences (Hard tabs, Show non-plaintext files, Full-text search) should be saved rather then be lost at the end of a session. I often use Textdrop on computers that I can't stay logged in to, so I end up setting these options each time I log in.

**Comment by dtjm** [comment]
These are saved in LocalStorage. Is yours being cleared out when logging out?

**Comment by elcste** [comment]
I'm usually using a private window.

**Comment by dtjm** [comment]
Ah, I don't think I can store settings client-side with private browsing enabled. I'll have to do it server side. I'll consider doing it if other users are interested also.

**Comment by elcste** [comment]
Thanks for considering it.

**Comment by bigcfk** [comment]
Hey! I'd would be interested in this feature, too.
