### ISSUE TITLE
Slow down the save interval (was: Flood of growl messages...)

### ISSUE THREAD

**Issue by sa1f** [dtjm/textdropapp.com#19]
I have growl enabled and with each word I write, there is a new notification. It really gets irritating after a while. This was an issue on version 2.2.2 when you had autosave enabled. Perhaps having an wait time of a minute or so would help or even going through an intermediate server before updating dropbox after the file is closed. But that'll also introduce a host of security issues (Dunno if that made sense)

**Comment by dtjm** [comment]
Yeah, that's what my desktop looks like while I'm developing. TextDrop is not really designed to be used on a computer where you actually have Dropbox installed, though.  What is your setup like? (In terms of how much computers do you use, how many have Dropbox installed, where you use TextDrop)

I am thinking of slowing down the save interval, though, if anything to reduce the load on the server.

**Comment by sa1f** [comment]
Yeah you're point is quite true. This might be the first time I'm using textdrop on a computer with dropbox installed. In that case, this not much of an issue then is it? I have Dropbox installed on one primary computer (laptop where I almost never use textdrop) and another PC, (never used textdrop). Mostly I use it to update my taskpaper list from school or work. All in all I think that this is a non-issue now.
