### ISSUE TITLE
Tab key functionality gone 

### ISSUE THREAD

**Issue by sa1f** [dtjm/textdropapp.com#20]
Version 2.2.2: Tab key worked normally (Inserted tabs in file)
Version 3.0.0: Tab key switches focus to some other element on page

**Comment by dtjm** [comment]
It's a bug! =) Good catch. Actually I left it out and wanted to see if anyone would notice.

**Comment by sa1f** [comment]
Question, how do you label an issue? (bug,enhancement,etc.)

**Comment by dtjm** [comment]
On the right side --------------------------------->>>>>

Underneath the green `Open` button.

**Comment by dtjm** [comment]
Actually it might be possible that you don't have permission to add labels though.

**Comment by dtjm** [comment]
fixed in dee748e

**Comment by micjoh** [comment]
still not possible to use tab in dokument.

**Comment by dtjm** [comment]
I won't be able to push out the fix until next week because my server support is out for the weekend.

**Comment by micjoh** [comment]
ok. then no problems so far
editing, saving, quitting. Not lost a character sofar. :-)

**Comment by dtjm** [comment]
Excellent. May we never lose a character!
