### ISSUE TITLE
Option: Always use Remote Version

### ISSUE THREAD

**Issue by CrystalDave** [dtjm/textdropapp.com#201]
Every time I load up TextDrop for my todo list (or my list of links to follow up on), it triggers a popup to the effect of 'Data has diverged between local and Dropbox. Would you like to override the remote changes with what's saved locally?' and I have to remember to click 'Cancel' rather than 'OK'.

I've gotten somewhat used to it, but it'd be nice to be able to set a setting to where it acts like I'm always going to click "Cancel" (or "OK", I could see someone using the flip side of this).

**Comment by dtjm** [comment]
@RS-David thanks for the feedback. Development has pretty much been put on pause as I've been super-busy, but I'm moving your ticket here where I am tracking new feature requests: https://trello.com/c/p6R7kjnY/9-option-always-use-remote-version
