### ISSUE TITLE
Internet connection loss (Offline mode)

### ISSUE THREAD

**Issue by sa1f** [dtjm/textdropapp.com#22]
Case 1:
1. Internet on
2. Do some editing -> Edits gets updated to dropbox
3. Turn Internet connection off
4. Do nothing
5. Turn connection on
6. Do some editing -> Dropbox gets updated
Conclusion: If you don't edit a file while there is no connection, updates will continue as normal after connection is restored. 

Case 2:
1. Internet on, do some editing -> works fine
2. Internet off, then do some editing -> No updates to dropbox
3. Turn internet back on, do some more editing -> No updates to dropbox
Conclusion: If you edit a file while there is no connection, any changes will be lost, even after connection is restored.

Suggestion: Do something like https://secure.motodiaryapp.com/w I believe they use localstorage to store files until connection is restored, after which they resync with the server.

**Comment by dtjm** [comment]
You are on a roll! This is a interesting idea...basically a sort of offline mode. I'm gonna flag this for version 3.1.

**Comment by dtjm** [comment]
Also I looked at motodiary, and it looks like they are using SQL storage in the browser, but I would probably go with localStorage myself.

**Comment by dtjm** [comment]
It should be more robust now. I made some changes that put your data in temporary storage (sessionStorage) which persists while the browser window is open.

**Comment by sa1f** [comment]
Works as expected :) 

## 

Saif Sajid

**Comment by dtjm** [comment]
Excellent!
