### ISSUE TITLE
Basic Area

### ISSUE THREAD

**Issue by Nizzer** [dtjm/textdropapp.com#23]
I managed to break it while still trying the basic functions.
I browsed around and opened a couple files. Edited one of them, fine no problem.
I went to log out and then log back in and got the following:

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by dtjm** [comment]
And we're off to a rocky start! =) I think I know what the issue is, now just waiting for our host to fix my git repo so I can push the fix out.

**Comment by Nizzer** [comment]
Ha Ha, no problem :) 
N
