### ISSUE TITLE
not possible to login

### ISSUE THREAD

**Issue by micjoh** [dtjm/textdropapp.com#26]
Not possible to login. I have to sign up everytime

**Comment by dtjm** [comment]
What browser are you using?

**Comment by micjoh** [comment]
safari for windows 5.1.4 and chrome dev channel- same on both. application error

**Comment by dtjm** [comment]
Ok thanks, I'll check it out. What version of Windows?

**Comment by micjoh** [comment]
windows 7 64 bit

**Comment by dtjm** [comment]
Do you mean that you can't access any files at all?

**Comment by micjoh** [comment]
tested in ie9 too. same problem. 

logged in to old textdrop with my old shortcut - ok
adressbar link http://textdropapp.com/
logged in to old textdrop from betapage - not ok
adressbar link http://http//old.textdropapp.com

**Comment by dtjm** [comment]
Ah, I see. The link is broken. Will be fixed in the next release.

**Comment by micjoh** [comment]
Login issue.
I tracked it down to the dropboxlogin. Cleared all caches and saved passwords on all browsers. Now I can login.
