### ISSUE TITLE
refresh filelist

### ISSUE THREAD

**Issue by micjoh** [dtjm/textdropapp.com#28]
If i rename a file in another program (writeroom)  I have to refresh page or logout and login for textdrop to be aware of the name change. It's not enough to navigate in and out of a folder. Is that ok?

**Comment by dtjm** [comment]
What I will probably do is whenever you enter a directory, check with Dropbox to see if any files have changed. I may also automatically check for changes every minute or so.

**Comment by micjoh** [comment]
In above scenario I have renamed a file in another program. textdrop is not aware of this. I can still edit the old file resulting in a new file when it is saved

**Comment by dtjm** [comment]
I have a fix which will be released soon.
