### ISSUE TITLE
"Error occurred in the application" (was: Can't log in.)

### ISSUE THREAD

**Issue by ajtb** [dtjm/textdropapp.com#29]
I saw a similar issue and it's been already closed, but nothing changed for me. I still can't log into the app.
"An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

Mac OSX 10.7.3, Chrome 18

**Comment by dtjm** [comment]
I closed the issue but am having problems pushing the fix out. Will leave this one open until its pushed.

**Comment by dtjm** [comment]
Should be good now.

**Comment by ajtb** [comment]
Great, can't wait to do some testing!
