### ISSUE TITLE
Uninformative Error Message Given for Binary Data Files

### ISSUE THREAD

**Issue by sebthedev** [dtjm/textdropapp.com#30]
When I try to open a file that isn't in a text format (such as a Powerpoint presentation), the only thing that appears in the viewing window is "� BINARY DATA �". This isn't a particularly informative message, and will probably confuse some non-tech savvy users.

I would like to suggest that a message such as "TextDropApp cannot show this filetype."

Mac OS 10.7.3, Chrome 17.0.963.79.

**Comment by dtjm** [comment]
Haha. See this is why you need beta testers. When I wrote it, I thought � BINARY DATA � was so clever and informative, but now I see your point.

**Comment by dtjm** [comment]
Fixed, and will be pushed in next release. I hope the new text is not overkill...
