### ISSUE TITLE
Making the File List small causes the dates to go out of alignment

### ISSUE THREAD

**Issue by sebthedev** [dtjm/textdropapp.com#31]
As seen in this image, if the width of the file browser is made very small, it causes the dates to go out of alignment further down the list. Ideally, the dates further down the list wouldn't jump down at all.

Mac OS X 10.7.3, Chrome 17.0.963.79

**Comment by dtjm** [comment]
Good catch.

**Comment by dtjm** [comment]
Fixed and will be pushed in next release.
