### ISSUE TITLE
Deleting Files

### ISSUE THREAD

**Issue by dkam136** [dtjm/textdropapp.com#32]
Is there a way to delete files in version 3 directly without signing in and doing it manually on the dropbox website?  I can't figure it out if there is.  

_Mac OS X Lion_
_Safari 5.1.1_

**Comment by dtjm** [comment]
Currently there is no way of deleting files. Is that something you would like to have?

**Comment by dkam136** [comment]
I don't think I would use it very often, but one thing that I found myself wanting to do in version 2 was rename a file without having to sign into dropbox to do it.  I think I would want to rename files more often than I would delete a file.  Since all of my students work from the same dropbox account, I sometimes find myself wanting to mass rename files they are working on (or that they did not listen to instructions and they need to rename a file) and there is no good way to do that unless I have the dropbox stored locally on my computer (which I do not because I have a different dropbox for personal and professional use already installed on my local computer).  I understand, however, that my needs might be different than the "average" user. 

Nice UI, btw.  I really like the way it feels like nvALT.  You did a really good job with that.  Perhaps that's why I want the ability to delete directly using something like the command + delete keyboard shortcut in nvALT.

**Comment by dtjm** [comment]
I'll keep this as a feature request for a future release. And yes, I think most of the UI credit can go to nvALT =)

**Comment by dtjm** [comment]
It's a secret feature right now because I'm not sure I have it down correctly, but try deleting files using `Shift-Ctrl-Backspace`. If there is a file currently open, it will delete that file. Otherwise, it will delete the file under the cursor if you are browsing in the file list view.

**Comment by dkam136** [comment]
Cool. It worked for me when I was using chrome.

**Comment by dtjm** [comment]
Oh...I forgot you are on OS X. You can do `Shift-Cmd-Backspace` also
