### ISSUE TITLE
SSL Broken?

### ISSUE THREAD

**Issue by sa1f** [dtjm/textdropapp.com#33]
I'm pretty sure you've already noticed this, but 'https' is crossed off. Is it because you're not following the (something).herokuapp.com ? Also, what're you using to build this?

**Comment by dtjm** [comment]
I have a certificate for www.textdropapp.com so once I move to that domain, the warning will go away.

**Comment by dtjm** [comment]
Also, a few things I'm using to build this:
- Heroku for deployment platform
- Node.js for server-side code
- Backbone.js for client-side code
