### ISSUE TITLE
Zooming in on Text

### ISSUE THREAD

**Issue by dkam136** [dtjm/textdropapp.com#34]
When I zoom in on text (command plus in safari), the sidebar also zooms in.  I would like to be able to zoom in on text without the sidebar also zooming in (for ease of reading).

**Comment by dtjm** [comment]
Not sure how this would work, I'll put it on the backlog for now.

**Comment by sa1f** [comment]
How 'bout having as a settings option? Kind of like [quietwrite](http://quietwrite.com) . I really think that it's a bad idea disabling a 'browser' feature.

**Comment by dtjm** [comment]
You can still use your browser zoom which is why I'm on the fence. You can hide the sidebar too by dragging it to the edge.

**Comment by bigcfk** [comment]
Some browsers have a "zoom text only" feature, too.

**Comment by dtjm** [comment]
Which browsers can do "zoom text only"? That's new to me.

**Comment by sa1f** [comment]
Well I know Safari and Firefox [do](http://imgur.com/a/n55pO). Dunno about the rest.

**Comment by dtjm** [comment]
That's cool, I had no idea about that. I'm still not seeing a huge benefit to having a custom zoom feature that only applies to the text. Right now you can do one of two things:
1. Hide the sidebar and use browser zoom
2. Adjust your browser default fixed-width font (that's what I'm using to draw the text area)
3. Convince me that you need a custom zoom feature
