### ISSUE TITLE
Search all files - (was: Feature Suggestion Thoughts)

### ISSUE THREAD

**Issue by bigcfk** [dtjm/textdropapp.com#36]
I wasn't sure where would be best to post feature suggestions, so here these are:

(the most useful)
- Using the search bar to search all files, not just the open directory.

(the more extraneous ones)
- Drag and Drop files into different folders?
- Option to hide ._files (mac hidden files) and other hidden files [these may just be something I need to delete]
- Icons rather than text links. [help] question mark symbol - [account] TextDrop Logo (old one) - [logout] Circle w/ Line.
- Perhaps a 'New Text/File' Button on the left of the search bar? (the new TextDrop logo with a + sign?)

**Comment by bigcfk** [comment]
And, perhaps a feature request list/wiki, so they can be noted down and not end up being re-suggested later?

**Comment by dtjm** [comment]
This is a good place to post feature requests. In the future though it would help if you split them up into issues so I can manage them individually. 

Broader search is a good idea, ill keep it in the dock. Those others will probably not make it though.

**Comment by ckhicks** [comment]
Definitely agree on searching all files (if possible) as that is one of the missing pieces in apps like nvALT. If you could find a way to work it in, that'd be amazing.

**Comment by dtjm** [comment]
+1 from http://www.macdrifter.com/2012/04/simplenote-and-trouble-in-paradise/

I will be working on this next.

**Comment by ckhicks** [comment]
Beautiful, excited to see your version in action!

**Comment by dtjm** [comment]
> And, perhaps a feature request list/wiki, so they can be noted down and not end up being re-suggested later

If TextDrop gets that popular, then that could be a good idea. I think this will do for now.

**Comment by dtjm** [comment]
Done!
