### ISSUE TITLE
New files not saving (was: Saving and deleting)

### ISSUE THREAD

**Issue by Nizzer** [dtjm/textdropapp.com#37]
I've noticed that newly typed text isn't saving at all.
Also, would it be possible to delete files?

**Comment by dtjm** [comment]
Not saving at all meaning new files aren't saved? Or text typed into existing files? Can you describe exactly what you are doing step by step? Thanks.

**Comment by Nizzer** [comment]
Sorry for not being clear.
The file is created and saved but text typed into it wasn't saving.
I created a new file - which took three or four attempts before the file would actually be created.
I typed in some text, waited for a while (about 20 secs), closed the file, opened it again and there was no text in it.

**Comment by dtjm** [comment]
Ok thanks, will check it out.

**Comment by dtjm** [comment]
Also, deleting files may be a future feature. I'm still on the fence about that one. But at least there's 2 of you that have requested it.

**Comment by Nizzer** [comment]
OK, thanks.

**Comment by dtjm** [comment]
Niz, I'm having trouble reproducing this bug. Can you try clearing your browser cache? You might still be have some old JavaScript files cached. Also what browser are you on?

**Comment by Nizzer** [comment]
Will do. I'll try what you suggest. 
I using Chrome on Win 7.

**Comment by dtjm** [comment]
Ok, I'll close this for now, but just post a comment here if it happens again and I'll re-open it.
