### ISSUE TITLE
Cannot Resize Filelist

### ISSUE THREAD

**Issue by bigcfk** [dtjm/textdropapp.com#39]
Filelist size resizer handle (?) went missing. Now I can't resize the filelist. Restarting the browser didn't reset it, either.

**Comment by dtjm** [comment]
Oops. What browser? The position gets stored in localStorage so you will have to clear your localStorage if you can.

**Comment by bigcfk** [comment]
This was in Chromium on MacOSX.
It's not happening now. So I'll see if it comes up again.

**Comment by dtjm** [comment]
Ok I'll close it for now. Leave a comment on this issue again if it comes back up.
