### ISSUE TITLE
Resizing During Markdown Preview

### ISSUE THREAD

**Issue by ckhicks** [dtjm/textdropapp.com#45]
Activating MD mode and resizing the file list/display pane causes strange shifts in content. Turning it off again and moving the slider back and forth fixes the issue.

http://grab.by/cs9k

Mac OS 10.6.8
Safari 5.1.4
Default User Agent (also broken when spoofing different UA)

**Comment by dtjm** [comment]
Note to self: possibly due inline `<h2>` element being rendered to the right edge of the file list view. Having the mouse near that edge causes the file list view to essentially scroll to the right to show text that is wider than the list view itself.

Possible solution: wrap the `<h2>` in a `<div>` make the div display:block but the h2 inline? Need one element to be inline to detect width to hide the date dynamically.

**Comment by dtjm** [comment]
should be fixed now
