### ISSUE TITLE
Editing non-text files causes truncation

### ISSUE THREAD

**Issue by ckhicks** [dtjm/textdropapp.com#46]
Ouch, I just edited the error message on a non-text file (MP3, in this case) and it ruined the copy on Dropbox. (Thank you, version tracking!) I'd suggest some kind of failsafe to not allow editing at all on files that are not txt/rtf/taskpaper/etc. I'm lucky I had a backup.

**Comment by dtjm** [comment]
Was it the message that said that the file could not be opened in Textdrop?

I have a couple of ways of preventing this from happening but I guess you got  past them all. 

What browser and OS was this on?

**Comment by ckhicks** [comment]
Woops, sorry, here are my stats:

Mac OS 10.6.8
Safari 5.1.4
Default User Agent

Let me know if you need me to replicate this on other browsers/etc.

I clicked on the MP3 file and it displayed your humorous message about how the file couldn't be opened. When I edited the text anyway and checked my local copy, it had truncated the file to a few bytes. Is there a way to just gray those non-text files out in the left pane?

**Comment by dtjm** [comment]
I can hide files if they are known non-text mime types like image/jpg (or audio/*).  But Dropbox doesn't always give me good mime types so I have to perform detection after the file is opened. But the text area should be disabled if a file is detected as non-text. 

In this case Dropbox probably is giving a good mime type but if there was say a text file with no extension it would just give me application/octet-stream. 

Actually can you tell me the mime type so I can put it on the blacklist? It should show on the error message.

**Comment by dtjm** [comment]
fixed. and yes, thank goodness Dropbox has rollback to previous versions. I've probably done that hundreds of times this past week.
