### ISSUE TITLE
"Welcome to TextDrop! Please start by paying here." Duplicated many times on payment screen.

### ISSUE THREAD

**Issue by sebthedev** [dtjm/textdropapp.com#53]
Once I've paid for my subscription, the text above is repeated many times. Please see <a href="http://dl.dropbox.com/u/96146/Screenshots/Snap%202012-03-22%20at%206.46.37%20PM.PNG">this screenshot</a>.

**Comment by dtjm** [comment]
I did see this also once, but I'm having a heck of a time trying to reproduce it. If anyone can reproduce it, please post the steps here.
