### ISSUE TITLE
editing simultaneous in two browsers

### ISSUE THREAD

**Issue by micjoh** [dtjm/textdropapp.com#59]
I've tried this several times with the same outcome using chrome and safari.

editing the same note simultaneous without explicitly refreshing the side after each sentence makes dropbox "lock" to one of the sessions. Thus what I write in the session that is locked will sync but the other will not and when you press the refresh page you loose all in that session and get what was written in the other.

for me it is not an issue per se. I wouldn' t use it that way but it is good to know

**Comment by dtjm** [comment]
Thanks I'll check it out.
