### ISSUE TITLE
Multi-document mode (was: Keyboard shortcuts)

### ISSUE THREAD

**Issue by shahidhussain** [dtjm/textdropapp.com#60]
The one thing that stops me from ditching textmate permanently is that there are only two keyboard shortcuts - search and markdown. (I'd argue that markdown doesn't need switching on / off that fast).

The killer for me is to be able to switch between open text files quickly. In TextMate I use opt+cmd+left / right, same as Chrome. Of course, you can't use the same shortcut, but something else would be great.

**Comment by bigcfk** [comment]
"Ctrl + ," and "Ctrl + ." might be good for switching between files (based on their < > symbols).
I'm not sure what other keyboard shortcuts would be necessary/plausible, other than 'return to home folder.' But I would suggest keeping shortcuts contained in one area of the keyboard. (i.e., from [K] to [Apostrophe], and [M] to [Backslash].) For one-handed ease, for (possibly) easier habituation, and for cool.

(btw, I feel the need to say somewhere how awesome TextDrop is. Seriously, I effing love this.)

**Comment by dtjm** [comment]
Wow first of all I never thought this could compete with Textmate, so :-0

So what were talking about here is a multi-document mode, possibly with tabs or some way of navigating between open documents. Very interesting, and actually I had not even thought of this before but it makes sense. This is a pretty major feature I'll have to chew on for a while.

**Comment by dtjm** [comment]
And @bigcfk thanks for the, uh, outburst of  emotion =)

**Comment by shahidhussain** [comment]
Being a muppet, I use very little of the capability of TextMate. However, for what I _do_ use it for, TextDrop absolutely could replace it. It's fast, it's online, it's awe-inspiring.

**Comment by dtjm** [comment]
I'm going to close the door on multi-document mode for now.
