### ISSUE TITLE
Change Markdown preview font (was: Markdown presentation)

### ISSUE THREAD

**Issue by shahidhussain** [dtjm/textdropapp.com#61]
Again not a bug, a preference.

I reckon that Markdown actually has three modes to it, not two.

1) Markdown totally off
2) Markdown highlight of source text (so a title still shows with a # )
3) Markdown output (so the title actually has a larger font size)

I'd also reckon that the right font for the first two is a monospace like courier, but the right font for the last one is _not_ courier - the usual sans serif would be great.

Right now, the markdown mode feels like a mix between modes 2 & 3 - although it's monospace font, it seems kinda like an output.

Anyway - this is totally all preference. This is just mine.

**Comment by dtjm** [comment]
I'm not clear on the three modes of Markdown that you describe. Is there another application that uses Markdown like this that you can provide as an example?

I do agree that monospace is not right for HTML output of markdown as it can be confusing.

**Comment by shahidhussain** [comment]
Kinda. I use TextMate on text files a lot. You can turn syntax highlighting for Markdown on / off (modes 1/2) and also a preview option (mode 3, access it with bundles -> markdown -> preview). Textmate does blend a little bit - for example, if you use italics syntax, it makes the text actually italics. However, it doesn't break the monospaced-ness of the font at any point.

I'm not saying textmate did it right, but I guess it's what I'm used to.

**Comment by dtjm** [comment]
Aha so #2 is syntax highlighting. I use that in Vim too for Markdown. Not sure if I want that in Textdrop though...that's really entering the arena of code editor.

**Comment by shahidhussain** [comment]
Ah, gotcha.

Ok - so in which case, you have modes 1 and 3. Markdown is kinda simple enough that it doesn't really _need_ syntax highlighting. Just out of curiosity, what's the use case for an editable-on-the-fly mode 3?

**Comment by dtjm** [comment]
Editing in Markdown preview mode might be useful once you set up your structure, it might be nice to be able to "touch up" without switching back. But it seems like there would be so many little nuances to consider when implementing such a mode, i wouldn't take it lightly. 

I am also considering having markdown preview as a split screen mode so you don't have to switch back and forth. What do you think about that?

**Comment by shahidhussain** [comment]
I personally don't use the markdown output, but if I did, this split screen mode would have me humping my laptop.

**Comment by dtjm** [comment]
Ok so I'll just put +1 from Shahid.

**Comment by dtjm** [comment]
Font changed and added issue for split screen #66
