### ISSUE TITLE
conflicted copy...

### ISSUE THREAD

**Issue by micjoh** [dtjm/textdropapp.com#62]
When I was actually editing a file for a length of time I got a lot(!) of conflicted copies:

1 - INBOX (michael johnson's conflicted copy) (michael johnson's conflicted copy) (1) (michael johnson's conflicted copy) (michael johnson's conflicted copy).taskpaper

**Comment by bigcfk** [comment]
Yeah, I ended up with a conflicted copy.

I had edited a file on my computer (DropBox app was not on), began using TextDrop on that file, and then turned on the DropBox app.

**Comment by dtjm** [comment]
Michael, can you give a list of steps to reproduce the problem? Thanks.

**Comment by dtjm** [comment]
I think I am going to not try to protect people too much if they decide to edit files in different places at the same time.

**Comment by micjoh** [comment]
Hi sorry for late reply. I've been away.
The fact is that I haven't been able to reproduce it.  It happened that
evening. Several times. maybe it was a problem on my end.

br /michael

On Mon, Mar 26, 2012 at 19:47, dtjm <
reply@reply.github.com

**Comment by dtjm** [comment]
No problem. Let me know if it happens again and you can reproduce it. 

Thanks
/sam
