### ISSUE TITLE
ctrl+l switches to omnibar in chrome

### ISSUE THREAD

**Issue by ajtb** [dtjm/textdropapp.com#65]
From what I understand from help section, there are currently  two keyboard shortcuts in TextDrop: ctrl+m for markdown preview, and ctrl+l for switching to search bar (inside the app). When used in Chrome, the second one switches to browsers omnibar instead.

**Comment by dtjm** [comment]
Will probably change the modifier combination to `Shift-Ctrl` for Windows/Linux and `Shift-Cmd` for Mac.
