### ISSUE TITLE
Button to hide sidebar file-picker

### ISSUE THREAD

**Issue by jjlumagbas** [dtjm/textdropapp.com#69]
I prefer the view without the sidebar since I open files only at the start of editing, otherwise to me it's better hidden away. I see that you can drag the sidebar to hide it, but it's that much more convenient if there were an extra button.

**Comment by dtjm** [comment]
So you are saying you would want a button that would hide the sidebar with a single click? What if you could double-click the divider to hide it?

**Comment by jjlumagbas** [comment]
So you are saying you would want a button that would hide the sidebar with a single click?

Yes.

What if you could double-click the divider to hide it?

That would do too. Could it be a single-click, though? Then it would
behave like a drawer?

On Thu, Mar 29, 2012 at 12:13 PM, dtjm
reply@reply.github.com
wrote:

**Comment by dtjm** [comment]
Ok I will think about it some more. I think my only concern is to make sure its clear that you can either drag it or click it. Also if someone clicks it on accident I want to make it so they don't feel like its gone forever and freak out. Maybe a little button on the divider with a little icon or something.

**Comment by jjlumagbas** [comment]
Sounds good. Thanks for being open to the idea.

On Fri, Mar 30, 2012 at 3:06 AM, dtjm
reply@reply.github.com
wrote:

**Comment by dtjm** [comment]
+1 from another user

**Comment by dtjm** [comment]
You can single click the divider now to hide the file browser.

**Comment by jjlumagbas** [comment]
nice. just tested it. thanks!

On Thu, Apr 5, 2012 at 2:07 PM, dtjm
reply@reply.github.com
wrote:

**Comment by dtjm** [comment]
=)
