### ISSUE TITLE
Menu items our of alignment in home area

### ISSUE THREAD

**Issue by sebthedev** [dtjm/textdropapp.com#72]
On all pages in the /home section of the app, the page title and "Help - Account - Log Out" links are not sitting in the grey menubar; they are floating lower. However, if I reload the page, these items jump back into their rightful places, and everything looks normal again.

See this image: <a href="http://dl.dropbox.com/u/96146/Screenshots/Snap%202012-03-29%20at%208.27.17%20AM.PNG">http://dl.dropbox.com/u/96146/Screenshots/Snap%202012-03-29%20at%208.27.17%20AM.PNG</a>

Mac OS X 10.7.3, Chrome 17.0.963.83

**Comment by dtjm** [comment]
Probably due to the change in CSS. Let me know if it happens again.
