### ISSUE TITLE
Editing an HTML file with a Redirect

### ISSUE THREAD

**Issue by sebthedev** [dtjm/textdropapp.com#73]
If I try to open an HTML file with a redirect in it, when I try to edit the file, the file loads, and then immediately activates the redirect, and takes me to the page that the redirect is sending me to, without letting me edit the file. This should not happen. Instead I should be simply allowed to edit the file.

The file in question is:
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head><meta http-equiv="REFRESH" content="0;url=http://www.zibity.com"></head>
<body>This page has moved to http://www.zibity.com. You will now be redirected.</body>
</html>`

Mac OS X 10.7.3, Chrome 17.0.963.83

**Comment by dtjm** [comment]
Mmm thanks that's a good one.  There are probably other HTML tags I should strip as well.

**Comment by dtjm** [comment]
At this point I'm just going to escape all HTML tags.
